/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_guid}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Info */
        get: operations["client_info_api_clients__client_guid__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/n3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products N3 */
        get: operations["products_n3_api_products_n3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/n4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products N4 */
        get: operations["products_n4_api_products_n4_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Orders */
        get: operations["search_orders_api_orders_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order Detail */
        get: operations["order_detail_api_orders__order_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeIn */
        AnalyzeIn: {
            /** Client Guid */
            client_guid: string;
            /** Order Lines */
            order_lines?: components["schemas"]["OrderLineIn"][];
        };
        /** AnalyzeOut */
        AnalyzeOut: {
            /** Client Guid */
            client_guid: string;
            /** Niche */
            niche?: string | null;
            /** Analysis1 Forgotten */
            analysis1_forgotten: components["schemas"]["ForgottenItem"][];
            /** Analysis2 Niche */
            analysis2_niche: components["schemas"]["NicheItem"][];
        };
        /** ClientInfoOut */
        ClientInfoOut: {
            /** Niche */
            niche?: string | null;
            /** Total Orders */
            total_orders: number;
        };
        /** ClientOut */
        ClientOut: {
            /** Client Guid */
            client_guid: string;
            /** Client Name */
            client_name: string;
            /** Niche */
            niche?: string | null;
        };
        /** ForgottenItem */
        ForgottenItem: {
            /** Type */
            type: string;
            /** N3 */
            n3: string;
            /** N4 */
            n4?: string | null;
            /** Item Guid */
            item_guid?: string | null;
            /** Order Count */
            order_count: number;
            /** Total Orders */
            total_orders: number;
            /** Frequency Pct */
            frequency_pct: number;
            /** Avg Qty */
            avg_qty: number;
            /** Current Qty */
            current_qty?: number | null;
            /** Priority */
            priority: string;
            /** Stock On */
            stock_on?: number | null;
            /** Stock In Transit */
            stock_in_transit?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NicheItem */
        NicheItem: {
            /** N3 */
            n3: string;
            /** N4 */
            n4?: string | null;
            /** Item Guid */
            item_guid?: string | null;
            /** Niche */
            niche: string;
            /** Niche Pct */
            niche_pct: number;
            /** Client Count */
            client_count: number;
            /** Total Clients */
            total_clients: number;
            /** Order Count */
            order_count: number;
            /** Total Orders */
            total_orders: number;
            /** Frequency Pct */
            frequency_pct: number;
            /** Client Bought Before */
            client_bought_before: boolean;
            /** Avg Qty Per Client */
            avg_qty_per_client: number;
            /** Priority */
            priority: string;
            /** Stock On */
            stock_on?: number | null;
            /** Stock In Transit */
            stock_in_transit?: number | null;
        };
        /** OrderDetailOut */
        OrderDetailOut: {
            /** Client */
            client: string;
            /** Lines */
            lines: components["schemas"]["OrderLineOut"][];
        };
        /** OrderLineIn */
        OrderLineIn: {
            /** N3 */
            n3: string;
            /** N4 */
            n4?: string | null;
            /** Item Guid */
            item_guid?: string | null;
            /**
             * Qty
             * @default 0
             */
            qty: number;
        };
        /** OrderLineOut */
        OrderLineOut: {
            /** N3 */
            n3: string;
            /** N4 */
            n4?: string | null;
            /** Item Guid */
            item_guid?: string | null;
            /** Qty */
            qty?: number | null;
        };
        /** OrderSearchOut */
        OrderSearchOut: {
            /** Order Num */
            order_num: string;
            /** Date */
            date?: string | null;
            /** Line Count */
            line_count: number;
            /** Client */
            client: string;
        };
        /** ProductN4Out */
        ProductN4Out: {
            /** N4 */
            n4: string;
            /** Item Guid */
            item_guid: string;
        };
        /** SyncStatusOut */
        SyncStatusOut: {
            /** Status */
            status: string;
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Row Count */
            row_count: number;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_clients_api_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"][];
                };
            };
        };
    };
    client_info_api_clients__client_guid__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    products_n3_api_products_n3_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    products_n4_api_products_n4_get: {
        parameters: {
            query: {
                n3: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductN4Out"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_orders_api_orders_search_get: {
        parameters: {
            query: {
                query: string;
                client_guid?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSearchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    order_detail_api_orders__order_num__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_num: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
